// بيانات تجريبية للوحة التحكم — استبدلها بالـ API الفعلي عند الدمج

import type {
  User, Project, Customer, Inquiry,
  DesignRequest, Product, BlogPost, Testimonial
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "أحمد العتيبي",
    email: "ahmed@goldenmile.com.sa",
    phone: "+966 50 123 4567",
    role: "admin",
    isActive: true,
    lastLogin: "2026-07-04T19:30:00Z",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "u2",
    name: "سارة المطيري",
    email: "sara@goldenmile.com.sa",
    phone: "+966 55 987 6543",
    role: "manager",
    isActive: true,
    lastLogin: "2026-07-04T15:20:00Z",
    createdAt: "2025-02-20T08:00:00Z",
  },
  {
    id: "u3",
    name: "خالد القحطاني",
    email: "khalid@goldenmile.com.sa",
    phone: "+966 56 555 1234",
    role: "editor",
    isActive: true,
    lastLogin: "2026-07-03T12:00:00Z",
    createdAt: "2025-03-10T08:00:00Z",
  },
  {
    id: "u4",
    name: "نورة الدوسري",
    email: "noura@goldenmile.com.sa",
    phone: "+966 53 444 5678",
    role: "editor",
    isActive: false,
    lastLogin: "2026-06-25T09:15:00Z",
    createdAt: "2025-04-05T08:00:00Z",
  },
  {
    id: "u5",
    name: "فهد الشمري",
    email: "fahad@goldenmile.com.sa",
    phone: "+966 54 333 9876",
    role: "viewer",
    isActive: true,
    lastLogin: "2026-07-02T16:45:00Z",
    createdAt: "2025-05-12T08:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "فيلا الياسمين السكنية",
    client: "عبدالله السبيعي",
    type: "residential",
    status: "in_progress",
    progress: 65,
    budget: 850000,
    spent: 552500,
    startDate: "2026-03-01",
    endDate: "2026-09-30",
    manager: "أحمد العتيبي",
    location: "الرياض - حي الياسمين",
    createdAt: "2026-02-15",
  },
  {
    id: "p2",
    name: "مجمع النخيل التجاري",
    client: "شركة النخيل القابضة",
    type: "commercial",
    status: "in_progress",
    progress: 42,
    budget: 2400000,
    spent: 1008000,
    startDate: "2026-04-15",
    endDate: "2027-01-31",
    manager: "سارة المطيري",
    location: "الرياض - طريق الملك فهد",
    createdAt: "2026-04-01",
  },
  {
    id: "p3",
    name: "شقة الحمراء - ديكور كامل",
    client: "منى الزهراني",
    type: "residential",
    status: "completed",
    progress: 100,
    budget: 180000,
    spent: 175000,
    startDate: "2025-11-01",
    endDate: "2026-02-28",
    manager: "أحمد العتيبي",
    location: "جدة - حي الحمراء",
    createdAt: "2025-10-20",
  },
  {
    id: "p4",
    name: "مستودع المنطقة الصناعية",
    client: "مؤسسة البناء الحديث",
    type: "industrial",
    status: "planning",
    progress: 15,
    budget: 1200000,
    spent: 180000,
    startDate: "2026-07-15",
    endDate: "2026-12-31",
    manager: "خالد القحطاني",
    location: "الرياض - المنطقة الصناعية الثانية",
    createdAt: "2026-06-20",
  },
  {
    id: "p5",
    name: "مكتب الشركة الرئيسي",
    client: "شركة ألفا للاستشارات",
    type: "commercial",
    status: "on_hold",
    progress: 30,
    budget: 420000,
    spent: 126000,
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    manager: "سارة المطيري",
    location: "الرياض - برج المملكة",
    createdAt: "2026-04-25",
  },
  {
    id: "p6",
    name: "قصر الديوان",
    client: "الشيخ منصور الرشيد",
    type: "residential",
    status: "in_progress",
    progress: 78,
    budget: 3200000,
    spent: 2496000,
    startDate: "2026-01-10",
    endDate: "2026-11-30",
    manager: "أحمد العتيبي",
    location: "الرياض - حي الندى",
    createdAt: "2025-12-15",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "عبدالله السبيعي",
    email: "abdullah.s@email.com",
    phone: "+966 50 111 2233",
    city: "الرياض",
    status: "active",
    totalSpent: 552500,
    projectsCount: 1,
    lastContact: "2026-07-04T10:30:00Z",
    source: "referral",
    createdAt: "2026-02-15",
  },
  {
    id: "c2",
    name: "شركة النخيل القابضة",
    email: "projects@palmholding.sa",
    phone: "+966 11 222 3344",
    city: "الرياض",
    status: "active",
    totalSpent: 1008000,
    projectsCount: 1,
    lastContact: "2026-07-03T14:00:00Z",
    source: "website",
    createdAt: "2026-04-01",
  },
  {
    id: "c3",
    name: "منى الزهراني",
    email: "mona.z@email.com",
    phone: "+966 55 666 7788",
    city: "جدة",
    status: "past",
    totalSpent: 175000,
    projectsCount: 1,
    lastContact: "2026-03-15T11:00:00Z",
    source: "social",
    createdAt: "2025-10-20",
  },
  {
    id: "c4",
    name: "محمد الغامدي",
    email: "m.ghamdi@email.com",
    phone: "+966 53 999 0011",
    city: "الدمام",
    status: "lead",
    totalSpent: 0,
    projectsCount: 0,
    lastContact: "2026-07-02T09:00:00Z",
    source: "ads",
    createdAt: "2026-07-02",
  },
  {
    id: "c5",
    name: "هند البلوي",
    email: "hind.b@email.com",
    phone: "+966 56 444 5566",
    city: "تبوك",
    status: "prospect",
    totalSpent: 0,
    projectsCount: 0,
    lastContact: "2026-06-28T16:30:00Z",
    source: "website",
    createdAt: "2026-06-28",
  },
  {
    id: "c6",
    name: "الشيخ منصور الرشيد",
    email: "office@alrasheed.sa",
    phone: "+966 50 888 9900",
    city: "الرياض",
    status: "active",
    totalSpent: 2496000,
    projectsCount: 1,
    lastContact: "2026-07-04T08:00:00Z",
    source: "referral",
    createdAt: "2025-12-15",
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: "i1",
    name: "محمد الحربي",
    email: "m.harbi@email.com",
    phone: "+966 55 123 9876",
    subject: "استفسار عن تشطيب فيلا",
    message: "السلام عليكم، أرغب بالحصول على عرض سعر لتشطيب فيلا مساحتها 400 م² في حي الملقا.",
    status: "new",
    priority: "high",
    source: "contact_form",
    createdAt: "2026-07-04T11:15:00Z",
  },
  {
    id: "i2",
    name: "ريم العسيري",
    email: "reem.a@email.com",
    phone: "+966 56 789 1234",
    subject: "تصميم داخلي لشقة",
    message: "أبحث عن مصمم داخلي لشقة 180 م²، التايب الحديث والكلاسيكي.",
    status: "in_progress",
    priority: "medium",
    assignedTo: "سارة المطيري",
    source: "design_studio",
    createdAt: "2026-07-03T14:30:00Z",
  },
  {
    id: "i3",
    name: "سلطان القاسم",
    email: "sultan.q@email.com",
    phone: "+966 50 444 1122",
    subject: "مقاولة مبنى تجاري",
    message: "نحتاج مقاول لمبنى تجاري 5 طوابق، الميزانية تقريباً 4 مليون.",
    status: "responded",
    priority: "high",
    assignedTo: "أحمد العتيبي",
    source: "contact_form",
    createdAt: "2026-07-02T10:00:00Z",
  },
  {
    id: "i4",
    name: "نوال الخالدي",
    email: "nawal.k@email.com",
    phone: "+966 53 666 3344",
    subject: "استشارة مجانية",
    message: "أرغب باستشارة مجانية قبل البدء بمشروع الديكور.",
    status: "closed",
    priority: "low",
    source: "phone",
    createdAt: "2026-06-30T16:45:00Z",
  },
  {
    id: "i5",
    name: "فهد المطيري",
    email: "f.mutairi@email.com",
    phone: "+966 54 222 8899",
    subject: "طلب عرض سعر",
    message: "أرجو إرسال عرض سعر لتركيب مطابخ وأثاث منزلي.",
    status: "new",
    priority: "medium",
    source: "contact_form",
    createdAt: "2026-07-04T08:20:00Z",
  },
];

export const mockDesignRequests: DesignRequest[] = [
  {
    id: "d1",
    customer: "ريم العسيري",
    projectName: "تصميم صالة معيشة فاخرة",
    roomType: "living",
    style: "modern",
    status: "in_design",
    budget: 45000,
    deadline: "2026-07-20",
    images: [],
    notes: "يفضل الألوان الذهبية والأسود مع لمسات خشبية.",
    createdAt: "2026-07-03",
  },
  {
    id: "d2",
    customer: "محمد الحربي",
    projectName: "غرفة نوم رئيسية",
    roomType: "bedroom",
    style: "luxury",
    status: "pending",
    budget: 35000,
    deadline: "2026-07-25",
    images: [],
    createdAt: "2026-07-04",
  },
  {
    id: "d3",
    customer: "هند البلوي",
    projectName: "مطبخ مفتوح",
    roomType: "kitchen",
    style: "minimal",
    status: "approved",
    budget: 60000,
    deadline: "2026-08-10",
    images: [],
    createdAt: "2026-06-28",
  },
  {
    id: "d4",
    customer: "سلطان القاسم",
    projectName: "مكتب إدارة فاخر",
    roomType: "office",
    style: "classic",
    status: "review",
    budget: 85000,
    deadline: "2026-08-15",
    images: [],
    createdAt: "2026-06-25",
  },
];

export const mockProducts: Product[] = [
  {
    id: "pr1",
    name: "طقم كنب مودرن ذهبي",
    sku: "GM-SF-001",
    category: "أثاث",
    price: 12500,
    stock: 8,
    sold: 24,
    status: "active",
    createdAt: "2026-04-01",
  },
  {
    id: "pr2",
    name: "ثريا كريستال فاخرة",
    sku: "GM-LT-002",
    category: "إنارة",
    price: 8900,
    stock: 3,
    sold: 12,
    status: "active",
    createdAt: "2026-04-05",
  },
  {
    id: "pr3",
    name: "مكتب مدير تنفيذي",
    sku: "GM-FR-003",
    category: "أثاث مكتبي",
    price: 9800,
    stock: 0,
    sold: 6,
    status: "out_of_stock",
    createdAt: "2026-03-15",
  },
  {
    id: "pr4",
    name: "سجادة فارسية 3×4",
    sku: "GM-DC-004",
    category: "ديكور",
    price: 4500,
    stock: 15,
    sold: 32,
    status: "active",
    createdAt: "2026-02-20",
  },
  {
    id: "pr5",
    name: "مرآة جدارية مزخرفة",
    sku: "GM-DC-005",
    category: "ديكور",
    price: 2200,
    stock: 20,
    sold: 18,
    status: "active",
    createdAt: "2026-05-10",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "10 أفكار لديكور صالات المعيشة العصرية 2026",
    slug: "living-room-ideas-2026",
    excerpt: "اكتشف أحدث صيحات الديكور لصالات المعيشة مع نصائح من خبرائنا...",
    author: "سارة المطيري",
    category: "ديكور",
    status: "published",
    views: 4521,
    likes: 287,
    publishedAt: "2026-06-15",
    createdAt: "2026-06-10",
  },
  {
    id: "b2",
    title: "كيف تختار ألوان الجدران المناسبة لمنزلك",
    slug: "wall-colors-guide",
    excerpt: "دليل شامل لاختيار الألوان حسب المساحة والإضاءة...",
    author: "أحمد العتيبي",
    category: "نصائح",
    status: "published",
    views: 3210,
    likes: 198,
    publishedAt: "2026-06-22",
    createdAt: "2026-06-18",
  },
  {
    id: "b3",
    title: "مشروع فيلا الياسمين: رحلة من التصميم للتنفيذ",
    slug: "yasmeen-villa-project",
    excerpt: "تابع معنا تفاصيل مشروع فيلا الياسمين بكل مراحله...",
    author: "خالد القحطاني",
    category: "مشاريع",
    status: "draft",
    views: 0,
    likes: 0,
    createdAt: "2026-07-01",
  },
  {
    id: "b4",
    title: "أخطاء شائعة في تشطيب المنازل",
    slug: "common-finishing-mistakes",
    excerpt: "تجنب هذه الأخطاء التي يقع فيها الكثيرون...",
    author: "سارة المطيري",
    category: "نصائح",
    status: "published",
    views: 5980,
    likes: 412,
    publishedAt: "2026-05-28",
    createdAt: "2026-05-20",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    customerName: "عبدالله السبيعي",
    customerRole: "صاحب فيلا الياسمين",
    rating: 5,
    content: "تجربة رائعة مع الميل الذهبي، احترافية عالية والتزام بالمواعيد. النتيجة فاقت توقعاتي.",
    status: "approved",
    featured: true,
    createdAt: "2026-06-30",
  },
  {
    id: "t2",
    customerName: "منى الزهراني",
    customerRole: "مالكة شقة الحمراء",
    rating: 5,
    content: "فريق محترف ومتعاون، أنصح بهم بشدة لكل من يبحث عن الجودة.",
    status: "approved",
    featured: true,
    createdAt: "2026-04-15",
  },
  {
    id: "t3",
    customerName: "محمد الغامدي",
    customerRole: "عميل محتمل",
    rating: 4,
    content: "تواصلت معهم لاستشارة وكانت الإفادة ممتازة، أنتظر البدء بمشروعي قريباً.",
    status: "pending",
    featured: false,
    createdAt: "2026-07-02",
  },
  {
    id: "t4",
    customerName: "هند البلوي",
    customerRole: "مصممة ديكور",
    rating: 5,
    content: "شراكة مثمرة وتعاون مثمر، أتمنى استمرار العلاقة المهنية.",
    status: "approved",
    featured: false,
    createdAt: "2026-06-10",
  },
];

// بيانات الـ Charts
export const revenueChartData = [
  { label: "يناير", value: 420000 },
  { label: "فبراير", value: 380000 },
  { label: "مارس", value: 520000 },
  { label: "أبريل", value: 680000 },
  { label: "مايو", value: 740000 },
  { label: "يونيو", value: 920000 },
  { label: "يوليو", value: 850000 },
];

export const projectsByTypeData = [
  { label: "سكني", value: 18, color: "#c8962e" },
  { label: "تجاري", value: 12, color: "#f0c75e" },
  { label: "صناعي", value: 4, color: "#d4a843" },
  { label: "مكاتب", value: 7, color: "#a07820" },
];

export const projectsByStatusData = [
  { label: "مكتملة", value: 24, color: "#10b981" },
  { label: "قيد التنفيذ", value: 8, color: "#c8962e" },
  { label: "تخطيط", value: 5, color: "#3b82f6" },
  { label: "متوقفة", value: 3, color: "#ef4444" },
];

export const inquiriesByMonthData = [
  { label: "يناير", value: 32 },
  { label: "فبراير", value: 28 },
  { label: "مارس", value: 45 },
  { label: "أبريل", value: 52 },
  { label: "مايو", value: 68 },
  { label: "يونيو", value: 84 },
  { label: "يوليو", value: 96 },
];

export const topCustomersData = [
  { name: "الشيخ منصور الرشيد", spent: 2496000, projects: 1 },
  { name: "شركة النخيل القابضة", spent: 1008000, projects: 1 },
  { name: "عبدالله السبيعي", spent: 552500, projects: 1 },
  { name: "منى الزهراني", spent: 175000, projects: 1 },
  { name: "مؤسسة البناء الحديث", spent: 180000, projects: 1 },
];